VERSION=0.6
CONSUL_VERSION=0.6.4

build:
	VERSION=$(VERSION) CONSUL_VERSION=$(CONSUL_VERSION) make -C $(VERSION)/consul
	VERSION=$(VERSION) CONSUL_VERSION=$(CONSUL_VERSION) make -C $(VERSION)/consul-agent
	VERSION=$(VERSION) CONSUL_VERSION=$(CONSUL_VERSION) make -C $(VERSION)/consul-server

